In [9]:
import pandas as pd

In [16]:
df = pd.read_csv('iris.csv',sep=',')

In [18]:
df.drop(['sepal_width'], axis=1)

     sepal_length  petal_length  petal_width  plant
0             5.1           1.4          0.2      0
1             4.9           1.4          0.2      0
2             4.7           1.3          0.2      0
3             4.6           1.5          0.2      0
4             5.0           1.4          0.2      0
5             5.4           1.7          0.4      0
6             4.6           1.4          0.3      0
7             5.0           1.5          0.2      0
8             4.4           1.4          0.2      0
9             4.9           1.5          0.1      0
10            5.4           1.5          0.2      0
11            4.8           1.6          0.2      0
12            4.8           1.4          0.1      0
13            4.3           1.1          0.1      0
14            5.8           1.2          0.2      0
15            5.7           1.5          0.4      0
16            5.4           1.3          0.4      0
17            5.1           1.4          0.3      0
18            5.7           1.7          0.3      0
19            5.1           1.5          0.3      0
20            5.4           1.7          0.2      0
21            5.1           1.5          0.4      0
22            4.6           1.0          0.2      0
23            5.1           1.7          0.5      0
24            4.8           1.9          0.2      0
25            5.0           1.6          0.2      0
26            5.0           1.6          0.4      0
27            5.2           1.5          0.2      0
28            5.2           1.4          0.2      0
29            4.7           1.6          0.2      0
..            ...           ...          ...    ...
120           6.9           5.7          2.3      2
121           5.6           4.9          2.0      2
122           7.7           6.7          2.0      2
123           6.3           4.9          1.8      2
124           6.7           5.7          2.1      2
125           7.2           6.0          1.8      2
126           6.2           4.8          1.8      2
127           6.1           4.9          1.8      2
128           6.4           5.6          2.1      2
129           7.2           5.8          1.6      2
130           7.4           6.1          1.9      2
131           7.9           6.4          2.0      2
132           6.4           5.6          2.2      2
133           6.3           5.1          1.5      2
134           6.1           5.6          1.4      2
135           7.7           6.1          2.3      2
136           6.3           5.6          2.4      2
137           6.4           5.5          1.8      2
138           6.0           4.8          1.8      2
139           6.9           5.4          2.1      2
140           6.7           5.6          2.4      2
141           6.9           5.1          2.3      2
142           5.8           5.1          1.9      2
143           6.8           5.9          2.3      2
144           6.7           5.7          2.5      2
145           6.7           5.2          2.3      2
146           6.3           5.0          1.9      2
147           6.5           5.2          2.0      2
148           6.2           5.4          2.3      2
149           5.9           5.1          1.8      2

[150 rows x 4 columns]

In [42]:
df.shape

(150, 5)

In [43]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  plant
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [44]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width  plant
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

In [48]:
print(df.min())
print(df.max())

print(df.min(1))
print(df.max(1))

# try with mean, sum, abs, std

sepal_length    4.3
sepal_width     2.0
petal_length    1.0
petal_width     0.1
plant           0.0
dtype: float64
sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
plant           2.0
dtype: float64
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6      0.0
7      0.0
8      0.0
9      0.0
10     0.0
11     0.0
12     0.0
13     0.0
14     0.0
15     0.0
16     0.0
17     0.0
18     0.0
19     0.0
20     0.0
21     0.0
22     0.0
23     0.0
24     0.0
25     0.0
26     0.0
27     0.0
28     0.0
29     0.0
      ...
120    2.0
121    2.0
122    2.0
123    1.8
124    2.0
125    1.8
126    1.8
127    1.8
128    2.0
129    1.6
130    1.9
131    2.0
132    2.0
133    1.5
134    1.4
135    2.0
136    2.0
137    1.8
138    1.8
139    2.0
140    2.0
141    2.0
142    1.9
143    2.0
144    2.0
145    2.0
146    1.9
147    2.0
148    2.0
149    1.8
Length: 150, dtype: float64
0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ...
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Length: 150, dtype: float64

In [15]:
#df[0]

ValueError: labels ['sepal_length'] not contained in axis

In [ ]:
df['sepal_length'][0]

In [ ]:
df['sepal_length'][0:5]

In [3]:
import numpy as np

In [ ]:
np_array = np.array([3,5,25,23])
print(np_array)

In [ ]:
set1 = set([3,5,234])
np_array1 = np.array(set1)
print(np_array1)

In [ ]:
np_array2 = np.ones((3,4),dtype=int)
print(np_array2)

In [ ]:
np_array3 = np.zeros((3,4),dtype=int)
print(np_array3)

In [ ]:
np_array4 = np.full((3,4),9)
print(np_array4)

In [ ]:
array = [2,45,634,23]
np_array = np.array(array)

In [ ]:
array+2

In [ ]:
np_array+2

In [ ]:
np.add(np_array,2)

In [ ]:
a = [[3,4],[5,6]]
b = [[2,5],[7,2]]

a*b

In [ ]:
np.matmul(a,b)

In [ ]:
np.multiply(a,b)

In [ ]:
np.divide(a,b)

In [49]:
np.random.rand()

0.954608323970883

In [5]:
np.random.rand(4,3)

array([[ 0.69979889,  0.91743163,  0.84170352],
       [ 0.03444632,  0.98686576,  0.6414054 ],
       [ 0.48979267,  0.19528005,  0.5105011 ],
       [ 0.78982386,  0.68116739,  0.19072514]])